# Generated by Django 4.0.6 on 2022-07-20 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skykingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 22, 24, 25, 328675)),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(default='booked', max_length=50),
        ),
    ]
